    version: 2.1

jobs:
  build:
    docker:
       - image: "circleci/python:3.6.4"

    steps:
      - checkout
      - run: python3 calculator.py

workflows:
  build_program:
  jobs:
    - build     